config/routes.rb
Rails.application.routes.draw do
  resources :openings
  resources :restaurants
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/opening.rb
class Opening < ActiveRecord::Base

	WEEKDAYS = ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"]

	def self.weekdays
    WEEKDAYS.map do |weekday|
      weekday
    end
	end

	SEASONS = ["Haute", "Basse", "Moyenne"]

	def self.seasons
    SEASONS.map do |season|
      season
    end
	end


end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	validates_format_of :email, :with => /@/


	COUNTRIES = ["BE", "FR", "LU", "NL"]

	def self.countries
    COUNTRIES.map do |country|
      country
    end
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/openings_controller.rb
class OpeningsController < ApplicationController
  before_action :set_opening, only: [:show, :edit, :update, :destroy]

  # GET /openings
  # GET /openings.json
  def index
    @openings = Opening.all
  end

  # GET /openings/1
  # GET /openings/1.json
  def show
  end

  # GET /openings/new
  def new
    @opening = Opening.new
    @weekdays = Opening.weekdays
    @seasons = Opening.seasons
  end

  # GET /openings/1/edit
  def edit
    @weedays = Opening.weekdays
    @seasons = Opening.seasons
  end

  # POST /openings
  # POST /openings.json
  def create
    @opening = Opening.new(opening_params)

    respond_to do |format|
      if @opening.save
        format.html { redirect_to @opening, notice: 'Opening was successfully created.' }
        format.json { render :show, status: :created, location: @opening }
      else
        format.html { render :new }
        format.json { render json: @opening.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /openings/1
  # PATCH/PUT /openings/1.json
  def update
    respond_to do |format|
      if @opening.update(opening_params)
        format.html { redirect_to @opening, notice: 'Opening was successfully updated.' }
        format.json { render :show, status: :ok, location: @opening }
      else
        format.html { render :edit }
        format.json { render json: @opening.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /openings/1
  # DELETE /openings/1.json
  def destroy
    @opening.destroy
    respond_to do |format|
      format.html { redirect_to openings_url, notice: 'Opening was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_opening
      @opening = Opening.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def opening_params
      params.require(:opening).permit(:weekday, :open, :close, :season)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
    @countries = Restaurant.countries
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :postcode, :city, :country, :email, :phone, :mobile, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController


	def index
		@restaurant = Restaurant.last
	end

	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/openings_helper.rb
module OpeningsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Acatrestbis" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Acatrestbis" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/openings/_form.html.erb
<%= simple_form_for(@opening) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <b><%= f.label :weekday %></b><br>
    <%= f.select :weekday, @weekdays, {prompt: false}, {class: "form-control"} %>
    <%= f.input :open %>
    <%= f.input :close %>
    <b><%= f.label :season %></b><br>
    <%= f.select :season, @seasons, {prompt: false}, {class: "form-control"} %>  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/openings/edit.html.erb
<h1>Editing Opening</h1>

<%= render 'form' %>

<%= link_to 'Show', @opening %> |
<%= link_to 'Back', openings_path %>

app/views/openings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Openings</h1>

<table>
  <thead>
    <tr>
      <th>Weekday</th>
      <th>Open</th>
      <th>Close</th>
      <th>Season</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @openings.each do |opening| %>
      <tr>
        <td><%= opening.weekday %></td>
        <td><%= opening.open %></td>
        <td><%= opening.close %></td>
        <td><%= opening.season %></td>
        <td><%= link_to 'Show', opening %></td>
        <td><%= link_to 'Edit', edit_opening_path(opening) %></td>
        <td><%= link_to 'Destroy', opening, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Opening', new_opening_path %>

app/views/openings/new.html.erb
<h1>New Opening</h1>

<%= render 'form' %>

<%= link_to 'Back', openings_path %>

app/views/openings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weekday:</strong>
  <%= @opening.weekday %>
</p>

<p>
  <strong>Open:</strong>
  <%= @opening.open %>
</p>

<p>
  <strong>Close:</strong>
  <%= @opening.close %>
</p>

<p>
  <strong>Season:</strong>
  <%= @opening.season %>
</p>

<%= link_to 'Edit', edit_opening_path(@opening) %> |
<%= link_to 'Back', openings_path %>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :postcode %>
    <%= f.input :city %>
    <b><%= f.label :country %></b><br>
      <%= f.select :country, @countries, {prompt: false}, {class: "form-control"} %>
    <%= f.input :email %>
    <%= f.input :phone %>
    <%= f.input :mobile %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Postcode</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Mobile</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.postcode %></td>
        <td><%= restaurant.email %></td>
        <td><%= restaurant.phone %></td>
        <td><%= restaurant.mobile %></td>
        <td><%= restaurant.description %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @restaurant.postcode %>
</p>

<p>
  <strong>City:</strong>
  <%= @restaurant.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @restaurant.country %>
</p>

<p>
  <strong>Email:</strong>
  <%= @restaurant.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @restaurant.phone %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @restaurant.mobile %>
</p>

<p>
  <strong>Description:</strong>
  <%= @restaurant.description %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="#general-info">Infos</a></li>
  <li role="presentation"><a href="#menu">Menu</a></li>
  <li role="presentation"><a href="#reservations">Réservations</a></li>
</ul>

<div class="container">


<section id="top-of-page">
  <img class="img-responsive" src="assets/header.jpg" alt="">
</section>

</div>
<!-- Page Content -->
<div class="container">
  <section id="general-info">
    <div class="row">
        <div class="col-lg-12 text-center">

        </div>
    </div>
    <!-- /.row -->
  </section>
</div>

<div class="container">
  <section id="menu">
    <div class="row">
        <div class="col-lg-12 text-center">
            <h2>Notre Menu</h2>

        </div>
    </div>
    <!-- /.row -->
  </section>
</div>

<div class="container">
  <section id="reservations">
    <div class="row">
        <div class="col-lg-12 text-center">
            <h2>Réservations</h2>

        </div>
    </div>
    <!-- /.row -->
  </section>
</div>

<div class="container">
  <section id="pictures">

    <div class="row">
        <div class="col-lg-12 text-center">
            <h2>Nos photos</h2>
        </div>
    </div>

    <div class="row">
      <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
          <img src="assets/photo-1.jpg" alt="...">
        </a>
      </div>
      <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
          <img src="assets/photo-2.jpg" alt="...">
        </a>
      </div>
      <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
          <img src="assets/photo-3.jpg" alt="...">
        </a>
      </div>
      <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
          <div class="embed-responsive embed-responsive-4by3">
            <iframe class="embed-responsive-item"  width="560" height="315" src="https://www.youtube.com/embed/meOvuCM21ik" frameborder="0" allowfullscreen>
            </iframe>
          </div>
        </a>
      </div>
    </div>
  </section>
</div>